const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];let pages=[],current=0,activeCat='Tất cả',opened=null,cropPts=[],stream=null,scanTimer=null,lastFrame=null,stable=0,lastShot=0,autoOn=true,detected=null;
const toast=t=>{let x=$('#toast');x.textContent=t;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),1900)};
const DB={db:null,open(){return new Promise((r,j)=>{let q=indexedDB.open('scanner-pro-v03',1);q.onupgradeneeded=()=>q.result.createObjectStore('docs',{keyPath:'id'});q.onsuccess=()=>{this.db=q.result;r()};q.onerror=()=>j(q.error)})},all(){return new Promise(r=>{let q=this.db.transaction('docs').objectStore('docs').getAll();q.onsuccess=()=>r(q.result||[])})},put(v){return new Promise(r=>{let q=this.db.transaction('docs','readwrite').objectStore('docs').put(v);q.onsuccess=()=>r()})},del(id){return new Promise(r=>{let q=this.db.transaction('docs','readwrite').objectStore('docs').delete(id);q.onsuccess=()=>r()})}};
function screen(id){$$('.screen').forEach(x=>x.classList.remove('active'));$('#'+id).classList.add('active');$$('nav button').forEach(x=>x.classList.toggle('on',x.dataset.go===id));$('.fab').style.display=id==='home'?'block':'none';$('nav').style.display=['editor','finish','viewer'].includes(id)?'none':'flex'}
function cssFilter(f){return f==='auto'?'contrast(1.13) brightness(1.05)':f==='document'?'contrast(1.36) brightness(1.1) saturate(.68)':f==='bw'?'grayscale(1) contrast(1.9)':f==='gray'?'grayscale(1) contrast(1.2)':'none'}
function loadImg(src){return new Promise(r=>{let i=new Image;i.onload=()=>r(i);i.src=src})}function dataURL(c,q=.9){return c.toDataURL('image/jpeg',q)}
function masterSrc(p){return p.master||p.orig||p.src}function ensureMaster(p){if(!p.master)p.master=p.orig||p.src;return p.master}
function detectPaper(c){let w=c.width,h=c.height,x=c.getContext('2d'),d=x.getImageData(0,0,w,h).data,lum=new Float32Array(w*h),sum=0;for(let i=0,p=0;i<d.length;i+=4,p++){let v=.299*d[i]+.587*d[i+1]+.114*d[i+2];lum[p]=v;sum+=v}let th=Math.max(105,sum/lum.length*1.08),xs=[],ys=[];for(let y=1;y<h-1;y+=2)for(let xx=1;xx<w-1;xx+=2){let p=y*w+xx;if(lum[p]>th){xs.push(xx);ys.push(y)}}if(xs.length<w*h*.08)return null;xs.sort((a,b)=>a-b);ys.sort((a,b)=>a-b);let x0=xs[Math.floor(xs.length*.04)],x1=xs[Math.floor(xs.length*.96)],y0=ys[Math.floor(ys.length*.04)],y1=ys[Math.floor(ys.length*.96)];if((x1-x0)*(y1-y0)<w*h*.28)return null;return[[x0/w,y0/h],[x1/w,y0/h],[x1/w,y1/h],[x0/w,y1/h]]}
function autoPaperCrop(c){
 let max=520,sc=Math.min(1,max/Math.max(c.width,c.height)),w=Math.max(120,Math.round(c.width*sc)),h=Math.max(120,Math.round(c.height*sc)),t=document.createElement('canvas');t.width=w;t.height=h;let x=t.getContext('2d');x.drawImage(c,0,0,w,h),d=x.getImageData(0,0,w,h).data;
 const rgb=(xx,y)=>{let p=(y*w+xx)*4;return[d[p],d[p+1],d[p+2]]},samples=[];
 for(let xx=0;xx<w;xx+=Math.max(1,Math.round(w/60))){samples.push(rgb(xx,2),rgb(xx,h-3))}
 for(let y=0;y<h;y+=Math.max(1,Math.round(h/60))){samples.push(rgb(2,y),rgb(w-3,y))}
 samples.sort((a,b)=>(a[0]+a[1]+a[2])-(b[0]+b[1]+b[2]));let mid=samples[Math.floor(samples.length/2)],br=mid[0],bg=mid[1],bb=mid[2];
 const score=(xx,y)=>{let p=(y*w+xx)*4,dr=d[p]-br,dg=d[p+1]-bg,db=d[p+2]-bb,lum=(d[p]+d[p+1]+d[p+2])/3,bl=(br+bg+bb)/3;return Math.sqrt(dr*dr+dg*dg+db*db)+Math.max(0,lum-bl)*.45};
 let col=new Float32Array(w),row=new Float32Array(h);
 for(let xx=0;xx<w;xx++){let s=0,n=0;for(let y=Math.round(h*.12);y<h*.88;y+=3){s+=score(xx,y);n++}col[xx]=s/n}
 for(let y=0;y<h;y++){let s=0,n=0;for(let xx=Math.round(w*.12);xx<w*.88;xx+=3){s+=score(xx,y);n++}row[y]=s/n}
 const bounds=a=>{let edgeN=Math.max(5,Math.round(a.length*.08)),base=0;for(let i=0;i<edgeN;i++)base+=(a[i]+a[a.length-1-i])/2;base/=edgeN;let peak=Math.max(...a),th=base+(peak-base)*.34,l=-1,r=-1,run=Math.max(3,Math.round(a.length*.012)),ok=i=>{let n=0;for(let k=0;k<run&&i+k<a.length;k++)if(a[i+k]>th)n++;return n>=run-1};for(let i=2;i<a.length*.48;i++)if(ok(i)){l=i;break}for(let i=a.length-3;i>a.length*.52;i--){let n=0;for(let k=0;k<run&&i-k>=0;k++)if(a[i-k]>th)n++;if(n>=run-1){r=i;break}}return[l,r,peak-base]};
 let [l,r,cConf]=bounds(col),[top,bot,rConf]=bounds(row);if(l<0||r<0||top<0||bot<0||r-l<w*.48||bot-top<h*.48||cConf<12||rConf<12)return null;
 let m=Math.max(2,Math.round(Math.min(w,h)*.004));l+=m;r-=m;top+=m;bot-=m;
 return [[l/w,top/h],[r/w,top/h],[r/w,bot/h],[l/w,bot/h]]
}
function quality(c){let w=120,h=Math.max(20,Math.round(120*c.height/c.width)),t=document.createElement('canvas');t.width=w;t.height=h;let x=t.getContext('2d');x.drawImage(c,0,0,w,h);let d=x.getImageData(0,0,w,h).data,m=0,a=[];for(let i=0;i<d.length;i+=4){let v=(d[i]+d[i+1]+d[i+2])/3;a.push(v);m+=v}m/=a.length;if(m<55)return'Quá tối';if(m>242)return'Quá sáng';let v=0,n=0;for(let y=1;y<h-1;y++)for(let z=1;z<w-1;z++){let p=y*w+z,L=4*a[p]-a[p-1]-a[p+1]-a[p-w]-a[p+w];v+=L*L;n++}return v/n<55?'Có thể bị mờ':''}
async function openCamera(){pages=[];current=0;$('#cameraUI').classList.remove('hidden');autoOn=$('#autoCapture').checked;$('#camAuto').textContent=autoOn?'AUTO':'TAY';try{stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'},width:{ideal:4096},height:{ideal:4096}},audio:false});$('#camVideo').srcObject=stream;detected=null;stable=0;$('#camStatus').textContent='Căn tài liệu vừa màn hình';scanTimer=null}catch(e){toast('Không mở được camera');closeCamera();openPhotoPicker('add')}}
function closeCamera(){clearInterval(scanTimer);scanTimer=null;stream?.getTracks().forEach(t=>t.stop());stream=null;$('#cameraUI').classList.add('hidden')}
function scanFrame(){let v=$('#camVideo');if(!v.videoWidth)return;let c=$('#detectCanvas'),w=180,h=Math.round(180*v.videoHeight/v.videoWidth);c.width=w;c.height=h;c.getContext('2d').drawImage(v,0,0,w,h);let d=detectPaper(c),poly=$('#edgePoly');detected=d;if(!d){poly.setAttribute('points','');stable=0;$('#camStatus').textContent='Đang tìm tài liệu…';return}poly.setAttribute('points',d.map(p=>p[0]*1000+','+p[1]*1000).join(' '));let raw=c.getContext('2d').getImageData(0,0,w,h).data,diff=999;if(lastFrame&&lastFrame.length===raw.length){diff=0;for(let i=0;i<raw.length;i+=40)diff+=Math.abs(raw[i]-lastFrame[i]);diff/=raw.length/40}lastFrame=new Uint8ClampedArray(raw);stable=diff<5?stable+1:0;$('#camStatus').textContent=stable>1?'Giữ yên…':'Đã thấy tài liệu';if(autoOn&&stable>=4&&Date.now()-lastShot>2200)snap()}
async function snap(){let v=$('#camVideo');if(!v.videoWidth||Date.now()-lastShot<700)return;lastShot=Date.now();let c=document.createElement('canvas'),vw=v.videoWidth,vh=v.videoHeight,box=v.getBoundingClientRect(),viewAR=box.width/box.height,srcAR=vw/vh,sx=0,sy=0,sw=vw,sh=vh;if(srcAR>viewAR){sw=vh*viewAR;sx=(vw-sw)/2}else if(srcAR<viewAR){sh=vw/viewAR;sy=(vh-sh)/2}c.width=Math.round(sw);c.height=Math.round(sh);c.getContext('2d').drawImage(v,sx,sy,sw,sh,0,0,c.width,c.height);let warn=quality(c),src=c.toDataURL('image/png'),corners=[[0,0],[1,0],[1,1],[0,1]];let ac=autoPaperCrop(c);if(ac){let cw=ac[1][0]-ac[0][0],ch=ac[3][1]-ac[0][1],edgeMax=Math.max(ac[0][0],ac[0][1],1-ac[1][0],1-ac[2][1]);if(cw<.82||ch<.82||edgeMax>.12)ac=null}let shot={src,master:src,orig:$('#keepOriginal').checked?src:null,rot:0,filter:$('#autoProcess').checked?'auto':'original',corners:ac||corners,warn,sourceW:c.width,sourceH:c.height,autoCrop:!!ac};if(ac){try{let im=await loadImg(src),z=homographyWarp(im,ac);shot.src=z.toDataURL('image/jpeg',.94)}catch(_){}}pages.push(shot);current=pages.length-1;$('#camCount').textContent=pages.length+' trang';$('#camStatus').textContent=ac?'Đã tự cắt ✓':'Không nhận được mép giấy';stable=0;closeCamera();renderEditor();screen('editor');setTimeout(()=>toast(ac?'AUTO CROP ✓ Đã tự cắt mép giấy':'AUTO CROP: chưa nhận được mép giấy'),80)}
$('#scanFab').onclick=$('#scanNav').onclick=openCamera;$('#camClose').onclick=()=>{closeCamera();screen('home')};$('#camDone').onclick=()=>{closeCamera();if(pages.length){renderEditor();screen('editor')}else screen('home')};$('#shutter').onclick=snap;$('#camAuto').onclick=()=>{autoOn=!autoOn;$('#camAuto').textContent=autoOn?'AUTO':'TAY'};
function readFiles(fs){[...fs].forEach(f=>{let r=new FileReader;r.onload=()=>{let im=new Image;im.onload=async()=>{let masterCanvas=document.createElement('canvas');masterCanvas.width=im.naturalWidth||im.width;masterCanvas.height=im.naturalHeight||im.height;let mx=masterCanvas.getContext('2d');mx.imageSmoothingEnabled=false;mx.drawImage(im,0,0);let master=dataURL(masterCanvas,1),ac=autoPaperCrop(masterCanvas);
 if(ac){let cw=ac[1][0]-ac[0][0],ch=ac[3][1]-ac[0][1],edgeMax=Math.max(ac[0][0],ac[0][1],1-ac[1][0],1-ac[2][1]);if(cw<.82||ch<.82||edgeMax>.12)ac=null}
 let corners=ac||[[.03,.03],[.97,.03],[.97,.97],[.03,.97]],src=master;if(ac){try{let z=homographyWarp(im,ac);src=z.toDataURL('image/jpeg',.94)}catch(_){src=master}}pages.push({src,master,orig:$('#keepOriginal').checked?master:null,rot:0,filter:'auto',corners,warn:quality(masterCanvas),sourceW:masterCanvas.width,sourceH:masterCanvas.height,autoCrop:!!ac});current=pages.length-1;renderEditor();screen('editor');toast(ac?'AUTO CROP ✓ Ảnh nhập đã tự cắt':'Ảnh nhập: chưa nhận được mép giấy')};im.src=r.result};r.readAsDataURL(f)})}
let pickerMode='new';
function openPhotoPicker(mode='add'){
 pickerMode=mode;
 let p=$('#picker');
 p.value='';
 // iOS/Safari is more reliable when the file input is reset before every user-gesture click.
 requestAnimationFrame(()=>p.click());
}
$('#picker').onchange=e=>{
 let files=[...e.target.files];
 e.target.value='';
 if(!files.length)return;
 if(pickerMode==='new'){pages=[];current=0}
 readFiles(files)
};
$('#importNav').onclick=()=>openPhotoPicker('new');
$('#addPage').onclick=()=>openPhotoPicker('add');$$('[data-go]').forEach(b=>b.onclick=()=>screen(b.dataset.go));$('#settingsBtn').onclick=()=>screen('settings');$('#settingsBack').onclick=()=>screen('home');$('#backBtn').onclick=()=>screen('home');
function renderEditor(){if(!pages.length)return screen('home');let p=pages[current];ensureMaster(p);let rw=p.sourceW||0,rh=p.sourceH||0,mp=rw&&rh?(rw*rh/1e6).toFixed(1):'?';let ri=$('#resolutionInfo');if(ri)ri.textContent=rw&&rh?'MASTER '+rw+' × '+rh+' · '+mp+' MP':'MASTER · giữ ảnh gốc';let ai=$('#autoCropInfo');if(ai)ai.textContent=p.autoCrop?'AUTO CROP ✓':'AUTO CROP · chưa nhận mép giấy';$('#mainImg').src=p.src;$('#mainImg').style.transform='rotate('+p.rot+'deg)';$('#mainImg').style.filter=cssFilter(p.filter);$$('.filters button').forEach(b=>b.classList.toggle('on',b.dataset.filter===p.filter));$('#thumbs').innerHTML=pages.map((x,i)=>'<div><img src="'+x.src+'" data-i="'+i+'" class="'+(i===current?'on':'')+'">'+(x.warn?'<small class="w">'+x.warn+'</small>':'')+'</div>').join('');$$('#thumbs img').forEach(x=>x.onclick=()=>{current=+x.dataset.i;renderEditor()})}
$$('.filters button').forEach(b=>b.onclick=()=>{pages[current].filter=b.dataset.filter;renderEditor()});$('#rotate').onclick=()=>{pages[current].rot=(pages[current].rot+90)%360;renderEditor()};$('#enhance').onclick=()=>{let p=pages[current];ensureMaster(p);p.filter='document';renderEditor();toast('Làm rõ: không phá hủy ảnh gốc')};$('#deletePage').onclick=()=>{pages.splice(current,1);current=Math.max(0,current-1);renderEditor()};$('#finishBtn').onclick=()=>{if(!pages.length)return;$('#docName').value='Tài liệu '+new Date().toLocaleDateString('vi-VN');screen('finish')};$('#finishBack').onclick=()=>screen('editor');
function homographyWarp(im,q){let P=q.map(p=>[p[0]*im.width,p[1]*im.height]),dist=(a,b)=>Math.hypot(a[0]-b[0],a[1]-b[1]),W=(dist(P[0],P[1])+dist(P[3],P[2]))/2,H=(dist(P[0],P[3])+dist(P[1],P[2]))/2,ratio=W/H;if(H>W&&ratio>.62&&ratio<.80){let area=Math.max(64,W*H);ratio=1/Math.sqrt(2);W=Math.sqrt(area*ratio);H=W/ratio}else if(W>H&&(1/ratio)>.62&&(1/ratio)<.80){let area=Math.max(64,W*H),r=Math.sqrt(2);W=Math.sqrt(area*r);H=W/r}let k=1;W=Math.max(8,Math.round(W));H=Math.max(8,Math.round(H));let src=document.createElement('canvas');src.width=im.width;src.height=im.height;src.getContext('2d').drawImage(im,0,0);let S=src.getContext('2d').getImageData(0,0,src.width,src.height).data,[[x0,y0],[x1,y1],[x2,y2],[x3,y3]]=P,dx1=x1-x2,dx2=x3-x2,dx3=x0-x1+x2-x3,dy1=y1-y2,dy2=y3-y2,dy3=y0-y1+y2-y3,den=dx1*dy2-dy1*dx2||1e-9,g=(dx3*dy2-dy3*dx2)/den,h=(dx1*dy3-dy1*dx3)/den,a=x1-x0+g*x1,b=x3-x0+h*x3,d=y1-y0+g*y1,e=y3-y0+h*y3,o=document.createElement('canvas');o.width=W;o.height=H;let ox=o.getContext('2d'),od=ox.createImageData(W,H),D=od.data;for(let j=0;j<H;j++){let v=j/(H-1);for(let i=0;i<W;i++){let u=i/(W-1),z=g*u+h*v+1,X=Math.min(src.width-1.01,Math.max(0,(a*u+b*v+x0)/z)),Y=Math.min(src.height-1.01,Math.max(0,(d*u+e*v+y0)/z)),xi=X|0,yi=Y|0,fx=X-xi,fy=Y-yi,p=(yi*src.width+xi)*4,t=(j*W+i)*4;for(let n=0;n<3;n++)D[t+n]=(S[p+n]*(1-fx)+S[p+4+n]*fx)*(1-fy)+(S[p+src.width*4+n]*(1-fx)+S[p+src.width*4+4+n]*fx)*fy;D[t+3]=255}}ox.putImageData(od,0,0);return o}
function scanEnhance(src,mode='auto'){let max=1100,sc=Math.min(1,max/Math.max(src.width,src.height)),w=Math.max(8,Math.round(src.width*sc)),h=Math.max(8,Math.round(src.height*sc)),c=document.createElement('canvas');c.width=w;c.height=h;let x=c.getContext('2d');x.drawImage(src,0,0,w,h);let id=x.getImageData(0,0,w,h),d=id.data,gw=Math.max(12,Math.round(w/32)),gh=Math.max(12,Math.round(h/32)),cols=Math.ceil(w/gw),rows=Math.ceil(h/gh),bg=new Float32Array(cols*rows);for(let gy=0;gy<rows;gy++)for(let gx=0;gx<cols;gx++){let sum=0,n=0;for(let yy=gy*gh;yy<Math.min(h,(gy+1)*gh);yy+=3)for(let xx=gx*gw;xx<Math.min(w,(gx+1)*gw);xx+=3){let p=(yy*w+xx)*4;sum+=(d[p]+d[p+1]+d[p+2])/3;n++}bg[gy*cols+gx]=sum/Math.max(1,n)}let out=new Uint8ClampedArray(d.length),strength=mode==='document'?1.08:.82;for(let y=0;y<h;y++){let fy=y/gh-.5,y0=Math.max(0,Math.floor(fy)),y1=Math.min(rows-1,y0+1),ty=Math.max(0,Math.min(1,fy-y0));for(let xx=0;xx<w;xx++){let fx=xx/gw-.5,x0=Math.max(0,Math.floor(fx)),x1=Math.min(cols-1,x0+1),tx=Math.max(0,Math.min(1,fx-x0)),b0=bg[y0*cols+x0]*(1-tx)+bg[y0*cols+x1]*tx,b1=bg[y1*cols+x0]*(1-tx)+bg[y1*cols+x1]*tx,B=b0*(1-ty)+b1*ty,p=(y*w+xx)*4;for(let k=0;k<3;k++){let v=d[p+k]+(238-B)*strength;v=(v-128)*1.12+128;out[p+k]=Math.max(0,Math.min(255,v))}out[p+3]=255}}let tmp=new ImageData(out,w,h),base=document.createElement('canvas');base.width=w;base.height=h;base.getContext('2d').putImageData(tmp,0,0);let o=document.createElement('canvas');o.width=src.width;o.height=src.height;let ox=o.getContext('2d');ox.imageSmoothingQuality='high';ox.filter='contrast(1.04)';ox.drawImage(base,0,0,o.width,o.height);ox.filter='none';ox.globalAlpha=.16;ox.globalCompositeOperation='overlay';ox.drawImage(base,-1,0,o.width,o.height);ox.globalAlpha=1;ox.globalCompositeOperation='source-over';return o}
function flatScan(src,mode='auto'){let sw=src.width,sh=src.height,ww=Math.min(520,sw),wh=Math.max(8,Math.round(sh*ww/sw)),small=document.createElement('canvas');small.width=ww;small.height=wh;let sx=small.getContext('2d');sx.imageSmoothingQuality='high';sx.drawImage(src,0,0,ww,wh);let sd=sx.getImageData(0,0,ww,wh).data,cell=Math.max(10,Math.round(ww/26)),cols=Math.ceil(ww/cell),rows=Math.ceil(wh/cell),grid=new Float32Array(cols*rows);for(let gy=0;gy<rows;gy++)for(let gx=0;gx<cols;gx++){let vals=[];for(let y=gy*cell;y<Math.min(wh,(gy+1)*cell);y+=3)for(let x=gx*cell;x<Math.min(ww,(gx+1)*cell);x+=3){let p=(y*ww+x)*4;vals.push(.299*sd[p]+.587*sd[p+1]+.114*sd[p+2])}vals.sort((a,b)=>a-b);grid[gy*cols+gx]=vals[Math.floor(vals.length*.78)]||220}let bg=document.createElement('canvas');bg.width=cols;bg.height=rows;let bx=bg.getContext('2d'),bi=bx.createImageData(cols,rows);for(let i=0;i<grid.length;i++){let v=grid[i];bi.data[i*4]=bi.data[i*4+1]=bi.data[i*4+2]=v;bi.data[i*4+3]=255}bx.putImageData(bi,0,0);let field=document.createElement('canvas');field.width=sw;field.height=sh;let fx=field.getContext('2d');fx.imageSmoothingEnabled=true;fx.imageSmoothingQuality='high';fx.filter='blur(18px)';fx.drawImage(bg,0,0,sw,sh);fx.filter='none';let base=document.createElement('canvas');base.width=sw;base.height=sh;base.getContext('2d').drawImage(src,0,0);let id=base.getContext('2d').getImageData(0,0,sw,sh),fd=fx.getImageData(0,0,sw,sh).data,d=id.data,strength=mode==='document'?1:.72;for(let i=0;i<d.length;i+=4){let B=(fd[i]+fd[i+1]+fd[i+2])/3,shift=(238-B)*strength;for(let k=0;k<3;k++){let v=d[i+k]+shift;v=(v-128)*(mode==='document'?1.12:1.055)+128;d[i+k]=Math.max(0,Math.min(255,v))}}base.getContext('2d').putImageData(id,0,0);return base}
async function processed(p,q=+$('#pdfQuality').value||.86){let im=await loadImg(masterSrc(p)),c=p.corners?homographyWarp(im,p.corners):(()=>{let z=document.createElement('canvas');z.width=im.width;z.height=im.height;z.getContext('2d').drawImage(im,0,0);return z})();let swap=p.rot%180!==0,o=document.createElement('canvas');o.width=swap?c.height:c.width;o.height=swap?c.width:c.height;let x=o.getContext('2d');x.imageSmoothingEnabled=true;x.imageSmoothingQuality='high';x.filter=cssFilter(p.filter);x.translate(o.width/2,o.height/2);x.rotate(p.rot*Math.PI/180);x.drawImage(c,-c.width/2,-c.height/2);return{url:o.toDataURL('image/jpeg',q),w:o.width,h:o.height}}
function b64(u){let s=atob(u.split(',')[1]),a=new Uint8Array(s.length);for(let i=0;i<s.length;i++)a[i]=s.charCodeAt(i);return a}
async function makePDF(srcPages=pages){let imgs=[];for(let p of srcPages)imgs.push(await processed(p));let objs=[],kids=[],add=o=>(objs.push(o),objs.length);add('');add('');for(let i=0;i<imgs.length;i++){let im=imgs[i],bytes=b64(im.url),io=add({h:'<< /Type /XObject /Subtype /Image /Width '+im.w+' /Height '+im.h+' /ColorSpace /DeviceRGB /BitsPerComponent 8 /Filter /DCTDecode /Length '+bytes.length+' >>\nstream\n',bytes,t:'\nendstream'}),pw=595.28,ph=841.89,dw=pw,dh=dw/(im.w/im.h);if(dh>ph){dh=ph;dw=dh*(im.w/im.h)}let s='q '+dw+' 0 0 '+dh+' '+((pw-dw)/2)+' '+((ph-dh)/2)+' cm /Im'+i+' Do Q',co=add('<< /Length '+s.length+' >>\nstream\n'+s+'\nendstream'),pg=add('<< /Type /Page /Parent 2 0 R /MediaBox [0 0 '+pw+' '+ph+'] /Resources << /XObject << /Im'+i+' '+io+' 0 R >> >> /Contents '+co+' 0 R >>');kids.push(pg+' 0 R')}objs[0]='<< /Type /Catalog /Pages 2 0 R >>';objs[1]='<< /Type /Pages /Kids ['+kids.join(' ')+'] /Count '+kids.length+' >>';let enc=new TextEncoder(),parts=[enc.encode('%PDF-1.4\n')],offs=[0],pos=parts[0].length;objs.forEach((o,i)=>{offs.push(pos);let a=enc.encode((i+1)+' 0 obj\n');parts.push(a);pos+=a.length;if(typeof o==='string'){a=enc.encode(o);parts.push(a);pos+=a.length}else{a=enc.encode(o.h);parts.push(a,o.bytes);pos+=a.length+o.bytes.length;a=enc.encode(o.t);parts.push(a);pos+=a.length}a=enc.encode('\nendobj\n');parts.push(a);pos+=a.length});let xr=pos,xt='xref\n0 '+(objs.length+1)+'\n0000000000 65535 f \n'+offs.slice(1).map(n=>String(n).padStart(10,'0')+' 00000 n \n').join('')+'trailer\n<< /Size '+(objs.length+1)+' /Root 1 0 R >>\nstartxref\n'+xr+'\n%%EOF';parts.push(enc.encode(xt));return new Blob(parts,{type:'application/pdf'})}
async function sharePDF(srcPages=pages,name=$('#docName').value||'Scanner-Pro'){toast('Đang tạo PDF…');let blob=await makePDF(srcPages),file=new File([blob],name.replace(/[\\/:*?"<>|]/g,'-')+'.pdf',{type:'application/pdf'});if(navigator.share&&navigator.canShare?.({files:[file]}))await navigator.share({files:[file],title:name});else{let a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=file.name;a.click()}}
let cacheDocs=[];async function refresh(){cacheDocs=(await DB.all()).sort((a,b)=>b.id-a.id);renderDocs()}
$('#saveDoc').onclick=async()=>{let name=$('#docName').value.trim()||'Tài liệu',cat=$('#docCat').value,stored=[];toast('Đang lưu…');for(let p of pages){let z=await processed(p,.8);stored.push({src:z.url,master:masterSrc(p),orig:p.orig,rot:p.rot,filter:p.filter,corners:p.corners?p.corners.map(q=>[...q]):null,warn:'',sourceW:p.sourceW,sourceH:p.sourceH})}await DB.put({id:Date.now(),name,cat,date:new Date().toLocaleString('vi-VN'),pages:stored});pages=[];await refresh();screen('home');toast('Đã lưu vào IndexedDB')};$('#exportPdf').onclick=()=>sharePDF();
function renderDocs(){let q=$('#search').value.toLowerCase(),d=cacheDocs.filter(x=>(activeCat==='Tất cả'||x.cat===activeCat)&&x.name.toLowerCase().includes(q));$('#empty').style.display=d.length?'none':'flex';$('#docs').innerHTML=d.map(x=>'<div class="doc" data-id="'+x.id+'"><img src="'+x.pages[0].src+'"><div class="meta"><b>'+x.name.replace(/</g,'&lt;')+'</b><small>'+x.pages.length+' trang · '+x.date+'</small><span class="tag">'+x.cat+'</span></div><span>›</span></div>').join('');$$('.doc').forEach(x=>x.onclick=()=>openDoc(+x.dataset.id))}
$('#search').oninput=renderDocs;$$('#chips .chip').forEach(b=>b.onclick=()=>{activeCat=b.dataset.cat;$$('#chips .chip').forEach(x=>x.classList.toggle('on',x===b));renderDocs()});
function openDoc(id){opened=cacheDocs.find(x=>x.id===id);if(!opened)return;$('#viewerTitle').textContent=opened.name;$('#viewerPages').innerHTML=opened.pages.map(p=>'<img src="'+p.src+'">').join('');screen('viewer')}$('#viewerBack').onclick=()=>screen('home');$('#viewerShare').onclick=()=>sharePDF(opened.pages,opened.name);$('#viewerMenu').onclick=async()=>{if(!opened)return;let n=prompt('Đổi tên tài liệu',opened.name);if(n===null)return;opened.name=n.trim()||opened.name;await DB.put(opened);await refresh();$('#viewerTitle').textContent=opened.name;toast('Đã đổi tên')};
$('#crop').onclick=openCrop;
function fitCropOverlay(){
 let st=$('#cropStage'),im=$('#cropImg'),svg=$('#cropSvg');
 if(!st||!im||!svg||!im.naturalWidth)return;
 let sr=st.getBoundingClientRect(),ir=im.getBoundingClientRect();
 svg.style.inset='auto';
 svg.style.left=(ir.left-sr.left)+'px';
 svg.style.top=(ir.top-sr.top)+'px';
 svg.style.width=ir.width+'px';
 svg.style.height=ir.height+'px';
}
function openCrop(){
 let p=pages[current];
 $('#cropImg').src=masterSrc(p);
 let q=p.corners||[[.05,.05],[.95,.05],[.95,.95],[.05,.95]];
 cropPts=q.map(x=>[x[0]*1000,x[1]*1000]);
 $('#cropModal').classList.remove('hidden');
 $('#cropImg').onload=()=>{fitCropOverlay();drawCrop()};
 requestAnimationFrame(()=>{fitCropOverlay();drawCrop()})
}
function drawCrop(){$('#cropSvg').setAttribute('viewBox','0 0 1000 1000');$('#cropPoly').setAttribute('points',cropPts.map(p=>p.join(',')).join(' '));$$('#cropSvg circle').forEach((c,i)=>{c.setAttribute('cx',cropPts[i][0]);c.setAttribute('cy',cropPts[i][1])})}
let drag=-1;
function svgPoint(e){let svg=$('#cropSvg'),pt=svg.createSVGPoint();pt.x=e.clientX;pt.y=e.clientY;let m=svg.getScreenCTM();if(!m)return{x:0,y:0};pt=pt.matrixTransform(m.inverse());return{x:Math.max(0,Math.min(1000,pt.x)),y:Math.max(0,Math.min(1000,pt.y))}}
function cropDown(e){e.preventDefault();let p=svgPoint(e),best=-1,bestD=1e9;for(let i=0;i<cropPts.length;i++){let dx=cropPts[i][0]-p.x,dy=cropPts[i][1]-p.y,d=Math.hypot(dx,dy);if(d<bestD){bestD=d;best=i}}let svg=$('#cropSvg'),rect=svg.getBoundingClientRect(),hit=120*1000/Math.max(rect.width,rect.height);if(best<0||bestD>hit)return;drag=best;cropPts[drag]=[p.x,p.y];drawCrop();try{svg.setPointerCapture(e.pointerId)}catch(_){}}
function cropMove(e){if(drag<0)return;e.preventDefault();let p=svgPoint(e);cropPts[drag]=[p.x,p.y];drawCrop()}
function cropUp(){drag=-1}
let cropLayer=$('#cropSvg');window.addEventListener('resize',()=>{if(!$('#cropModal').classList.contains('hidden')){fitCropOverlay();drawCrop()}});cropLayer.onpointerdown=cropDown;cropLayer.onpointermove=cropMove;cropLayer.onpointerup=cropUp;cropLayer.onpointercancel=cropUp;
$('#cropCancel').onclick=()=>$('#cropModal').classList.add('hidden');$('#cropOk').onclick=async()=>{let p=pages[current];p.corners=cropPts.map(x=>[x[0]/1000,x[1]/1000]);ensureMaster(p);p.corners=cropPts.map(x=>[x[0]/1000,x[1]/1000]);let oldFilter=p.filter;p.filter='original';let z=await processed(p,.9);p.filter=oldFilter;p.src=z.url;p.warn='';$('#cropModal').classList.add('hidden');renderEditor();toast('Đã lưu khung nắn · ảnh gốc không đổi')};
DB.open().then(refresh);if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js?v=053stable6');