const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
let pages=[],current=0,rotation=0,filter='original';
const toast=t=>{let x=$('#toast');x.textContent=t;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),1800)};
function screen(id){$$('.screen').forEach(x=>x.classList.remove('active'));$('#'+id).classList.add('active');$$('nav button').forEach(x=>x.classList.toggle('on',x.dataset.go===id));$('.fab').style.display=id==='home'?'block':'none'}
function readFiles(files){[...files].forEach(f=>{let r=new FileReader;r.onload=()=>{pages.push({src:r.result,rot:0,filter:'auto'});current=pages.length-1;renderEditor();screen('editor')};r.readAsDataURL(f)})}
$('#camera').onchange=e=>readFiles(e.target.files);$('#picker').onchange=e=>readFiles(e.target.files);$('#scanFab').onclick=$('#scanNav').onclick=()=>$('#camera').click();$('#importNav').onclick=()=>$('#picker').click();$('#addPage').onclick=()=>$('#camera').click();
$$('[data-go]').forEach(b=>b.onclick=()=>screen(b.dataset.go));$('#settingsBtn').onclick=()=>screen('settings');$('#settingsBack').onclick=()=>screen('home');$('#backBtn').onclick=()=>screen('home');
function cssFilter(f){return f==='auto'?'contrast(1.12) brightness(1.04)':f==='document'?'contrast(1.3) brightness(1.08) saturate(.75)':f==='bw'?'grayscale(1) contrast(1.75)':f==='gray'?'grayscale(1) contrast(1.15)':'none'}
function renderEditor(){if(!pages.length)return screen('home');let p=pages[current];$('#mainImg').src=p.src;$('#mainImg').style.transform=`rotate(${p.rot}deg)`;$('#mainImg').style.filter=cssFilter(p.filter);$$('.filters button').forEach(b=>b.classList.toggle('on',b.dataset.filter===p.filter));$('#thumbs').innerHTML=pages.map((x,i)=>`<img src="${x.src}" data-i="${i}" class="${i===current?'on':''}">`).join('');$$('#thumbs img').forEach(x=>x.onclick=()=>{current=+x.dataset.i;renderEditor()})}
$$('.filters button').forEach(b=>b.onclick=()=>{pages[current].filter=b.dataset.filter;renderEditor()});$('#rotate').onclick=()=>{pages[current].rot=(pages[current].rot+90)%360;renderEditor()};$('#enhance').onclick=()=>{pages[current].filter='document';renderEditor();toast('Đã tăng độ rõ tài liệu')};$('#deletePage').onclick=()=>{pages.splice(current,1);current=Math.max(0,current-1);renderEditor()};
function processedData(p){return new Promise(res=>{let im=new Image;im.onload=()=>{let swap=p.rot%180!==0,w=swap?im.height:im.width,h=swap?im.width:im.height,scale=Math.min(1,1800/Math.max(w,h));let c=document.createElement('canvas');c.width=w*scale;c.height=h*scale;let x=c.getContext('2d');x.filter=cssFilter(p.filter);x.translate(c.width/2,c.height/2);x.rotate(p.rot*Math.PI/180);x.drawImage(im,-im.width*scale/2,-im.height*scale/2,im.width*scale,im.height*scale);res({url:c.toDataURL('image/jpeg',.88),w:c.width,h:c.height})};im.src=p.src})}
function b64bytes(u){let s=atob(u.split(',')[1]),a=new Uint8Array(s.length);for(let i=0;i<s.length;i++)a[i]=s.charCodeAt(i);return a}
async function makePDF(){if(!pages.length)return;toast('Đang tạo PDF…');let imgs=[];for(let p of pages)imgs.push(await processedData(p));let objs=[],kids=[];const add=s=>{objs.push(s);return objs.length};let catalog=add(''),pagesObj=add('');for(let i=0;i<imgs.length;i++){let im=imgs[i],bytes=b64bytes(im.url),imgObj=add({head:`<< /Type /XObject /Subtype /Image /Width ${im.w} /Height ${im.h} /ColorSpace /DeviceRGB /BitsPerComponent 8 /Filter /DCTDecode /Length ${bytes.length} >>\nstream\n`,bytes,tail:'\nendstream'});let A4=[595.28,841.89],ratio=im.w/im.h,pw=A4[0],ph=A4[1],dw=pw,dh=dw/ratio;if(dh>ph){dh=ph;dw=dh*ratio}let x=(pw-dw)/2,y=(ph-dh)/2,content=`q ${dw.toFixed(2)} 0 0 ${dh.toFixed(2)} ${x.toFixed(2)} ${y.toFixed(2)} cm /Im${i} Do Q`;let cont=add(`<< /Length ${content.length} >>\nstream\n${content}\nendstream`);let pg=add(`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 ${pw} ${ph}] /Resources << /XObject << /Im${i} ${imgObj} 0 R >> >> /Contents ${cont} 0 R >>`);kids.push(`${pg} 0 R`)}objs[0]='<< /Type /Catalog /Pages 2 0 R >>';objs[1]=`<< /Type /Pages /Kids [${kids.join(' ')}] /Count ${kids.length} >>`;let parts=[new TextEncoder().encode('%PDF-1.4\n%âãÏÓ\n')],offs=[0],pos=parts[0].length;for(let i=0;i<objs.length;i++){offs.push(pos);let o=objs[i],head=new TextEncoder().encode(`${i+1} 0 obj\n`);parts.push(head);pos+=head.length;if(typeof o==='string'){let b=new TextEncoder().encode(o);parts.push(b);pos+=b.length}else{let h=new TextEncoder().encode(o.head);parts.push(h,o.bytes);pos+=h.length+o.bytes.length;let t=new TextEncoder().encode(o.tail);parts.push(t);pos+=t.length}let end=new TextEncoder().encode('\nendobj\n');parts.push(end);pos+=end.length}let xref=pos,xt=`xref\n0 ${objs.length+1}\n0000000000 65535 f \n`+offs.slice(1).map(n=>String(n).padStart(10,'0')+' 00000 n \n').join('')+`trailer\n<< /Size ${objs.length+1} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`;parts.push(new TextEncoder().encode(xt));let blob=new Blob(parts,{type:'application/pdf'}),name='Scanner-Pro-'+new Date().toISOString().slice(0,10)+'.pdf',file=new File([blob],name,{type:'application/pdf'});if(navigator.share&&navigator.canShare?.({files:[file]})){await navigator.share({files:[file],title:name})}else{let a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click()}saveDoc();}
$('#savePdf').onclick=makePDF;
function saveDoc(){let thumb=pages[0]?.src;if(!thumb)return;let docs=JSON.parse(localStorage.getItem('scannerDocs')||'[]');docs.unshift({name:'Tài liệu quét',date:new Date().toLocaleDateString('vi-VN'),count:pages.length,thumb});try{localStorage.setItem('scannerDocs',JSON.stringify(docs.slice(0,8)))}catch(e){}renderDocs()}
function renderDocs(){let docs=JSON.parse(localStorage.getItem('scannerDocs')||'[]');$('#empty').style.display=docs.length?'none':'flex';$('#docs').innerHTML=docs.map(d=>`<div class="doc"><img src="${d.thumb}"><div class="meta"><b>${d.name}</b><small>${d.count} trang · ${d.date}</small><span class="tag">Công việc</span></div><span>⋮</span></div>`).join('')}
renderDocs();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js');